name: Ruleset_TreasuryStockAvailability
description: Ruleset for Rules used in Treasury Stock Availability
version: '1.4'
author: nathan+business@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: rulesettreasurystockavailability
  parentArtefactID: westpacbusiness
  buildSystem: wheel
  author: null
  createdAt: '2024-05-23 11:53:46'
pipelines:
  pipelines/test_rule:
    name: test_rule
    description: ''
    author: nathan+business@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-23 11:53:46'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/AddRule:
      name: AddRule
      category: Transform
      subCategory: ''
      description: null
      author: nathan+business@prophecy.io
      mode: batch
      files:
      - westpacbusiness_rulesettreasurystockavailability/gems/AddRule.py
      gemType: ComponentGem
      dependencies: null
      createdAt: '2024-05-23 11:57:59'
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-23 11:53:46'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules:
    businessRules/Rule1_ParseMaturityDate:
      name: Rule1_ParseMaturityDate
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
    businessRules/Rule2_DefaultLocation:
      name: Rule2_DefaultLocation
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
    businessRules/Rule3_DefaultGL_Level_1:
      name: Rule3_DefaultGL_Level_1
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
    businessRules/Rule4_DefaultGL_Level_2:
      name: Rule4_DefaultGL_Level_2
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
    businessRules/Rule5_DefaultGL_Level_3:
      name: Rule5_DefaultGL_Level_3
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
    businessRules/Rule6_ParseCouponRate:
      name: Rule6_ParseCouponRate
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
    businessRules/Rule7_ExcludeFlag:
      name: Rule7_ExcludeFlag
      description: Return Exclude = 'Y' is trade_type is 'loan'. Otherwise, 'N'
      tags: []
      inputs: []
      outputs: []
      author: nathan+business@prophecy.io
      createdAt: '2022-12-15 18:04:50'
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-05-23T11:53:46.839099Z'
  name: plibMaven
  version: 7.1.100
  id: '1628529435'
  createdAt: '2024-05-23T11:53:46.839099Z'
  type: plibMaven
- modifiedAt: '2024-05-23T11:53:46.839099Z'
  name: plibPypi
  version: 1.8.23
  id: '1225465421'
  createdAt: '2024-05-23T11:53:46.839099Z'
  type: plibPypi
projectDependencies:
  '225':
    projectUID: 225
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_225.git&subPath=
    version: 0.0.6
    isDefault: true
    author: null
    createdAt: '2024-05-23 11:53:27'
  '224':
    projectUID: 224
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_224.git&subPath=
    version: 0.2.14
    isDefault: true
    author: null
    createdAt: '2024-05-23 11:53:27'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
